all:   stream_server   stream_client  dgram_server  dgram_client  fork1   fork2    fork2

stream_server:  stream_server.c
			gcc -o stream_server stream_server.c
			chmod 700  stream_server

stream_client:  stream_client.c
			gcc -o stream_client stream_client.c
			chmod 700  stream_client

dgram_server:  dgram_server.c
			gcc -o dgram_server dgram_server.c
			chmod 700  dgram_server

dgram_client:  dgram_client.c
			gcc -o dgram_client dgram_client.c
			chmod 700  dgram_client

fork1:	fork1.c
	gcc -o fork1   fork1.c
	chmod 700  fork1

fork2:	fork2.c
	gcc -o fork2   fork2.c
	chmod 700  fork2

fork1:	fork3.c
	gcc -o fork3   fork3.c
	chmod 700  fork3




          

